# Generated by Django 4.1.7 on 2023-04-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_amenities_alter_room_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='toilet',
            new_name='toilets',
        ),
    ]
