# Generated by Django 4.0.10 on 2023-04-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rename_toilet_room_toilets'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='long_description',
            field=models.TextField(default=''),
        ),
    ]
